### PR TITLE
Fixed an issue with Android N's OpenJDK where invalid instantiator is…

### PR DESCRIPTION
**Pull request by taivokasper**
Fixed Objenesis for Android N preview.

### CODE REVIEW

**Comment by henri-tremblay** [comment]
One question: Why are you using the bootclasspath content to deduce the version? Why not using the Android version?

**Comment by henri-tremblay** [comment]
This is a fix for #37

**Comment by taivokasper** [comment]
Current Android N preview reports 23 as the version not 24. From bootclasspath I can detect whether it uses OpenJDK or not so it seems more reliable to depend on it. I found the solution from [this thread](https://github.com/RuedigerMoeller/fast-serialization/issues/121#issuecomment-205993211).

**Comment by Wavesonics** [comment]
A dev from Android comments in that thread that my boot class fix actually isn't a great idea, and we should use reflection to test for the Sun/Oracle method, if it does not exist, then skip the Objenesis stuff.

**Comment by henri-tremblay** [comment]
@Wavesonics: Yes. PlatformDescription.getAndroidVersion0 is doing pretty much that. So, I'll do a mashup of that and the pull request

**Comment by henri-tremblay** [comment]
I've modified your code to use UnsafeFactoryInstantiator. ObjectStreamClassInstantiator should be used only to get a serialization like behavior. However, I was surprised to see SunReflectionFactoryInstantiator not working. The ReflectionFactory class is part of the openjdk. Someone knows why it has disappeared?

**Pull request merged**
