### PR TITLE
enable GitHub Actions

### PR DESCRIPTION
**Pull request by sullis**
- add ci.yml workflow
- remove TravisCI

Resolves https://github.com/easymock/objenesis/issues/88

### CODE REVIEW

**Comment by sullis** [comment]
@henri-tremblay

**Comment by henri-tremblay** [comment]
Why using that over Travis?

**Comment by sullis** [comment]
@henri-tremblay Ready for review.

**Comment by henri-tremblay** [comment]
Awesome! Android installation is missing and then activating -Pall profile. But that is definitely a good start. Android is broken anyway I think... I need to partially move to gradle to fix it.

**Pull request merged**
